<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Cart */
/** @var $quoteViewModel Scommerce\TrackingBase\ViewModel\Checkout\Onepage */
$viewModel = $block->getData('view_model');
$quoteViewModel = $block->getData('quote_view_model');

$_mode = $block->getMode();
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!$helper->isEnhancedEcommerceEnabled()) return;
?>
<script>
    window.scTrackingContainer.setPageType('cart');

    let data = <?php echo json_encode($viewModel->getCrosssellProductsData())?>;
    window.scTrackingContainer.setImpressionListData(data);
    window.scTrackingContainer.setData('total', <?php echo $quoteViewModel->getTotalValue() ?>);
    let cartData = <?php echo json_encode($quoteViewModel->getProductsData()) ?>;
    window.scTrackingContainer.setData('cart', cartData);

    window.scTrackingContainer.fire('page_ready', window.scTrackingContainer.getPageType().toLowerCase());
    window.scTrackingContainer.fire('view_cart', cartData);
</script>
