<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Checkout\Success */
$viewModel = $block->getData('view_model');
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!($helper->isEnabled() && $helper->isEnhancedEcommerceEnabled())) return;
?>

<script type="text/javascript"<?= $viewModel->getHelper()->getNonce(); ?>>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking();

        let data = <?php echo json_encode($viewModel->getPurchaseData())?>;
        tracking.setPurchaseData(data);
        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "purchase");

        <?php if ($helper->isEnhancedConversionEnabled()): ?>
            let conversionDataToSet = <?php echo json_encode($viewModel->getConversionData())?>;
            let conversionItems = <?php echo json_encode($viewModel->getConversionItems()) ?>;
            tracking.setData('conversion_items', conversionItems);
            tracking.setData('conversion_pii', conversionDataToSet);
        <?php endif; ?>
    });
</script>


