<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Cart */
/** @var $quoteViewModel Scommerce\TrackingBase\ViewModel\Checkout\Onepage */
$viewModel = $block->getData('view_model');
$quoteViewModel = $block->getData('quote_view_model');

$_mode = $block->getMode();
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!$helper->isEnhancedEcommerceEnabled()) return;
?>

<script>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking();
        tracking.setPageType('cart');

        let data = <?php echo json_encode($viewModel->getCrosssellProductsData())?>;
        tracking.setImpressionListData(data);
        tracking.setData('total', <?php echo $quoteViewModel->getTotalValue() ?>);
        let cartData = <?php echo json_encode($quoteViewModel->getProductsData()) ?>;
        tracking.setData('cart', cartData);

        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "cart");
        tracking.fire('view_cart', cartData);
    });
</script>
