<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\ListProduct */
$viewModel = $block->getData('view_model');

$_mode = $block->getMode();
$viewModel->setMode($_mode);
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!$helper->isEnabled() || !$helper->isEnhancedEcommerceEnabled() || $helper->isCategoryAjaxEnabled()) return;

$_SIOSEnabled = $helper->isSIOSEnabled();
$_PICText = $helper->getPICText();
$cats = $viewModel->getRemarketingCategories();
?>

<script type="text/javascript"<?= $viewModel->getNonce(); ?>>
    require([
        "jquery",
        "scTrackingData",
        "jqueryViewport"
    ], function($, Tracking) {
        let tracking = Tracking();
        let intCtr = 0;
        let lastCtr = 0;

        tracking.setData('category', '<?php echo $block->escapeJs($viewModel->getCategoryName()) ?>');
        tracking.setData('category_full', '<?php echo $block->escapeJs($cats['full']) ?>');
        tracking.setData('category_plain', '<?php echo $block->escapeJs($cats['plain']) ?>');

        let data = <?php echo json_encode($viewModel->getProductsData())?>;
        <?php if (($_SIOSEnabled) && strlen($_PICText)):
        $productItemClass = $_PICText;
        if (strlen($productItemClass) == 0) $productItemClass = "div.products ol.product-items li.product-item";
        ?>
        tracking.setImpressionListData(data, true);

        $(document).ready(function () {
            $('<?php echo $productItemClass?>').inviewport({
                threshold: <?php echo $helper->getScrollThreshold(); ?>
            });
        });
        $(window).bind("scroll load", function() {
            let scrollImpressions = [];
            $('.in-view').each(function(){
                let id = this;
                let classNames = $(this).attr('class');
                $.each(tracking.getData('productList'), function (index, product) {
                    let pos = classNames.indexOf('impressionSent');
                    if (pos < 0 && index >= intCtr) {
                        $(id).addClass('impressionSent');
                        let impression = {
                            'id': product.id,
                            'name': product.name,
                            'price': product.price,
                            'category': product.category,
                            'brand': product.brand,
                            'list': product.list,
                            'position': product.position
                        }
                        scrollImpressions.push(impression);
                        intCtr++;
                        return false;
                    }
                });
            });
            if (intCtr > 0 && lastCtr < intCtr) {
                tracking.fire('listing_scroll', scrollImpressions);
                lastCtr = intCtr;
            }
        });
        <?php else: ?>
        tracking.setImpressionListData(data);
        <?php endif; ?>

        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "category");
    });
</script>
