<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $viewModel \Scommerce\TrackingBase\ViewModel\ViewProduct
 */
$viewModel = $block->getData('view_model');
$viewModel->setBlock($block);
$cats = $viewModel->getRemarketingCategories();
if (!$viewModel->getHelper()->isEnabled()) return;
?>

<script>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking();
        tracking.setData('category_full', '<?php echo $block->escapeJs($cats['full']) ?>');
        tracking.setData('category_plain', '<?php echo $block->escapeJs($cats['plain']) ?>');

        let data = <?php echo json_encode($viewModel->getProductData())?>;
        tracking.setProductData(data);
        let relatedData = <?php echo json_encode($viewModel->getRelatedProducts())?>;
        tracking.setImpressionListData(relatedData);
        let upsellData = <?php echo json_encode($viewModel->getUpsellProducts())?>;
        tracking.setImpressionListData(upsellData);

        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "product");
    });
</script>
