<?php
/**
 * @var IWD\CheckoutConnector\Block\Shortcut\PayPalButton $block
 */

$containerId = $block->getContainerId();
$merchantId = $block->getMerchantId() ? $block->getMerchantId() : ''
?>
<?php if($block->getPaypalStatus()): ?>
    <script>
        if (typeof window.paypal === 'undefined') {
            let scriptParams = {
                "client-id": "<?= $block->getClientId() ?>",
                "commit": "false",
                "intent": "authorize",
                "components": "buttons,messages",
                "vault": "false",
                "merchant-id": "<?= $merchantId ?>",
                "currency": "<?= $block->getCurrencyCode() ?>",
                "data-partner-attribution-id": "<?= $block->getPayPalBnCode() ?>"
            };

            let enableFunding = "<?= $block->getEnableFundingParam() ?>";
            if(enableFunding !== "") {
                scriptParams['enable-funding'] = enableFunding;
            }

            window.paypalLoadScript(scriptParams);
        }
    </script>
    <div class="custom-cart-message-wrap">
        <span><?= __('OR Checkout With:')?></span>
    </div>
    <div id='<?= $containerId ?>' class="iwd-paypal-wrapper" data-mage-init='<?= $block->getJsonConfig($containerId) ?>'></div>
<?php endif; ?>