<?php
/** @var $block Scommerce\TrackingBase\Block\Checkout\Multisuccess */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Checkout\Multisuccess */

$viewModel = $block->getData('view_model');

$helper = $viewModel->getHelper();
if (!($helper->isEnabled() && $helper->isEnhancedEcommerceEnabled())) return;

$order = $block->getOrder();

echo $this->getLayout()
    ->createBlock('Scommerce\TrackingBase\Block\Checkout\Order')
    ->setTemplate('Scommerce_TrackingBase::checkout/order.phtml')
    ->setData('view_model', $viewModel)
    ->setFirstOrder($order)
    ->toHtml();
?>
<div style="display: none;">
<?php
$additionalOrders = $block->getAdditionalOrders();
foreach ($additionalOrders as $id => $incId) : ?>
    <iframe src="<?php echo $block->escapeUrl($block->getUrl("sctracking/index/order?id=" . $incId . "&token=" . $block->getToken($id, $incId))); ?>"></iframe>
<?php endforeach; ?>
</div>
