<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Checkout\Onepage */
$viewModel = $block->getData('view_model');

$_mode = $block->getMode();
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!($helper->isEnabled() && $helper->isEnhancedEcommerceEnabled())) return;
$shipmentStep = 'shipment';
$paymentStep = 'payment';
?>

<script data-breeze <?= $helper->getNonce(); ?>>
    require([
        "jquery",
        "scTrackingData",
        'Magento_Checkout/js/model/quote',
        'Magento_Customer/js/model/customer'
    ], function($, Tracking, quote, customer) {
        let tracking = Tracking;

        let data = <?php echo json_encode($viewModel->getProductsData())?>;
        let sentSteps = [];
        let old_shipping = '', old_payment = '';

        tracking.setCartData(data);
        tracking.setData('total', <?php echo $viewModel->getTotalValue() ?>);
        tracking.setData('coupon', '<?php echo $viewModel->getCoupon() ?>');
        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "checkout");

        <?php if ($helper->getAddPaymentTitle()): ?>
        var paymentMethods = <?php echo json_encode($viewModel->getPaymentsList()) ?>;
        function getPaymentTitle(payment) {
            if (payment.title !== undefined) {
                return payment.title;
            }
            for (var i = 0; i < paymentMethods.length; i++) {
                if (paymentMethods[i].code == payment.method) {
                    return paymentMethods[i].title;
                }
            }
            return '<?php echo __('Unknown') ?>';
        }
        <?php endif; ?>

        function stepSent(step) {
            for (let i = 0; i < sentSteps.length; i++) {
                if (sentSteps[i] === step) return true;
            }
            return false;
        }

        function steps(value, pos) {
            if (value != undefined) {
                if (stepSent(pos) === false) {
                    sentSteps.push(pos);
                    tracking.setCheckoutStep({step: pos, option: value, products: tracking.getCartData(), pos});
                } else {
                    tracking.setCheckoutOption({step: pos, option: value, products: tracking.getCartData(), pos});
                }
            }
        }

        quote.shippingMethod.subscribe(function(newVal) {
            if (newVal == undefined) {
                return;
            }
            let shipping;
            <?php if ($helper->getAddCarrierTitle()): ?>
            shipping = newVal.carrier_code + '::' + quote.shippingMethod().method_title;
            <?php else: ?>
            shipping = newVal.carrier_code;
            <?php endif; ?>
            if (shipping != undefined && old_shipping != shipping) {
                old_shipping = shipping;
                steps(shipping, '<?php echo $shipmentStep ?>');
            }
        });

        quote.paymentMethod.subscribe(function(newVal) {
            if (newVal == undefined) {
                return;
            }
            let payment;
            <?php if ($helper->getAddPaymentTitle()): ?>
            payment = newVal.method + "::" + getPaymentTitle(newVal);
            <?php else: ?>
            payment = newVal.method;
            <?php endif; ?>
            if (payment != undefined && old_payment != payment) {
                old_payment = payment;
                steps(payment, '<?php echo $paymentStep ?>');
            }
        });

    });
</script>
