<?php
/** @var $block Scommerce\TrackingBase\Block\Checkout\Order */
/** @var $viewModel Scommerce\TrackingBase\ViewModel\Checkout\Multisuccess */
$viewModel = $block->getData('view_model');
$viewModel->setBlock($block);

$helper = $viewModel->getHelper();
if (!($helper->isEnabled() && $helper->isEnhancedEcommerceEnabled())) return;
?>

<script data-breeze>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking;

        let data = <?php echo json_encode($viewModel->getPurchaseData()) ?>;
        tracking.setPurchaseData(data);
        tracking.fire('page_ready', tracking.getPageType()?.toLowerCase() || "purchase");
    });
</script>
