<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Gtm
 */
?>
<?php
$helper = $this->getHelper();
if ($helper->isEnhancedEcommerceEnabled()):
    ?>
    <?php
    $addedProduct = $this->getAddToBasketData();
    $removedProduct = $this->getRemoveFromBasketData();
    if ($addedProduct || $removedProduct):?>
        <script>
            //<![CDATA[
            function manipulationOfCart(product, type, list) {
                //product = eval("(" + product + ")");

                if (type == 'add') {
                    dataLayer.push({
                        'event': 'addToCart',
                        'ecommerce': {
                            'currencyCode': product.currency,
                            'add': {                                // 'add' actionFieldObject measures.
                                'products': [{                        //  adding a product to a shopping cart.
                                    'name': product.name,
                                    'id': product.id,
                                    'price': product.price,
                                    'brand': product.brand,
                                    'category': product.category,
                                    'quantity': product.qty,
                                    'list': list
                                }]
                            }
                        }
                    });
                }
                else if (type == 'remove') {
                    dataLayer.push({
                        'event': 'removeFromCart',
                        'ecommerce': {
                            'currencyCode': product.currency,
                            'remove': {                                // 'remove' actionFieldObject measures.
                                'products': [{                        //  adding a product to a shopping cart.
                                    'name': product.name,
                                    'id': product.id,
                                    'price': product.price,
                                    'brand': product.brand,
                                    'category': product.category,
                                    'quantity': product.qty,
                                    'list': list
                                }]
                            }
                        }
                    });
                }
            }
            <?php if ($addedProduct):?>
            require(['jquery', 'mage/cookies'], function($){
                $(window).load(function() {
                    var productToBasket = <?php echo $addedProduct?>;
                    var impression = scGetProductImpression(productToBasket.allSkus);
                    var list = '';
                    if (impression != '') {
                        list = impression.list;
                    }
                    if (list == '') {
                        if (productToBasket.list == undefined || productToBasket.list == '') {
                            list = 'Category - ' + productToBasket.category;
                        } else {
                            list = productToBasket.list;
                        }
                    }

                    if (productToBasket != undefined) {
                        manipulationOfCart(productToBasket, 'add', list);
                    }
                    <?php $this->unsAddToBasketData();?>
                });
            });
            <?php endif;?>

            <?php if ($removedProduct):?>
            require(['jquery', 'mage/cookies'], function($){
                $(window).load(function() {
                    var productOutBasket = <?php echo $removedProduct?>;

                    if (productOutBasket != undefined) {
                        manipulationOfCart(productOutBasket, 'remove', '');
                    }
                    <?php $this->unsRemoveFromBasketData();?>
                });
            });
            <?php endif;?>
            //]]>
        </script>
    <?php endif;?>
<?php endif;?>

<!-- Scommerce Mage Google Tag Manager -->
<?php if ($helper->isGDPRCookieEnabled()): ?>
    <script>
        require([
            'jquery',
            'mage/cookies'
        ], function($) {

            var cookieKey = '<?php echo $helper->getCookieKey(); ?>';
            var isGDPRCookieForceDeclined = !!'<?php echo $helper->isGDPRCookieForceDeclined() ?>';

            function needShowTag() {
                if (cookieKey.length == 0) return true;
                var cookie = $.cookie('<?php echo $helper->getCookieKey() ?>');
                if (!isGDPRCookieForceDeclined) {
                    if (cookie == null || cookie == "0") {
                        return false;
                    } else {
                        return true;
                    }
                } else {
                    if (cookie == "1") {
                        return true;
                    } else {
                        return false;
                    }
                }
            }

            if (needShowTag() == true) {
                (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','<?php echo $helper->getAccountId() ?>');
            }
        });
    </script>
<?php else: ?>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $helper->getAccountId() ?>');</script>
<?php endif; ?>
<!-- Scommerce Mage End Google Tag Manager -->
