<?php
/**
 *
 * @var $block Scommerce\GoogleTagManagerPro\Block\ImpressionList
 */
?>

<?php
$helper = $this->getHelper();
$_productCollection = $this->getProductCollection();
$_JsProducts = $this->getJsProducts();
$_JsProductUrls = $this->getJsProductUrls();
$_impressionList = $this->getImpressionList();
$_categoryName = $this->getCategory();

$_SIOSEnabled = $helper->isSIOSEnabled();
$_PICText = $helper->getPICText();

$_productUrls = array();
$_products = array();

if ($_productCollection) {
    $_loop = 1;
    foreach ($_productCollection as $_product) {
        $_productUrls[] = $_product->getProductUrl();

        $_products[] = array(
            'id' => $this->escapeJsQuote($_product->getSku()),
            'name' => $this->escapeJsQuote($_product->getName()),
            'category' => $helper->getProductCategoryName($_product),
            'brand' => $this->escapeJsQuote($helper->getBrand($_product)),
            'list' => $this->escapeJsQuote($_impressionList),
            'price' => $helper->productPrice($_product),
            'url' => $_product->getProductUrl(),
            'position' => $_loop
        );
        $_loop++;
    }

    $_JsProducts = json_encode($_products);
    $_JsProductUrls = json_encode($_productUrls);
}

?>

<script type='text/javascript'>
    //<![CDATA[
    window.scProducts = window.scProducts || [];
    window.scProductUrls = window.scProductUrls || [];
    require(['jquery'], function($) {
        $('form[data-role=tocart-form]').each(function () {
            var elCat = $(this).find('input[name=sc_category]');
            if (elCat.length == 0) {
                $(this).append("<input type='hidden' name='sc_category' value='<?php echo $this->escapeHtmlAttr($_categoryName) ?>'/><input type='hidden' name='sc_list' value='<?php echo $this->escapeHtmlAttr($_impressionList) ?>'/>");
            }
        });
    });
    <?php if (($_SIOSEnabled) && strlen($_PICText)):
    $productItemClass = $_PICText;
    if (strlen($productItemClass)==0) $productItemClass = "div.products ol.product-items li.product-item";?>
    var jsProducts    = <?php echo $_JsProducts ?>;
    var jsProductUrls = <?php echo $_JsProductUrls ?>;
    var jsClickLabel  = '<?php echo $_impressionList?>';
    var intCtr = 0;
    var lastCtr = 0;

    Array.prototype.push.apply(window.scProducts, <?php echo $_JsProducts; ?>);
    Array.prototype.push.apply(window.scProductUrls, <?php echo $_JsProductUrls; ?>);

    require(['jquery', 'jqueryviewport'], function($) {
        $(document).ready(function () {
            $('<?php echo $productItemClass?>').inviewport({
                threshold: <?php echo $helper->getScrollThreshold(); ?>
            });
        });
        $(window).bind("scroll load", function() {
            var JsonObj = {};
            JsonObj.impressions = [];
            //console.log($('.in-view').size());
            $('.in-view').each(function(){
                var id = this;
                var classNames = $(this).attr('class');
                $.each(jsProducts, function (index, product) {
                    var pos = classNames.indexOf('impressionSent');
                    if (pos < 0 && index>=intCtr){
                        $(id).addClass('impressionSent');
                        var impression = {
                            'id': product.id,
                            'name': product.name,
                            'price': product.price,
                            'category': product.category,
                            'brand': product.brand,
                            'list': product.list,
                            'position': product.position
                        }
                        JsonObj.impressions.push(impression);
                        intCtr++;
                        return false;
                    }
                });
            });
            if (intCtr > 0 && lastCtr < intCtr) {
                window.dataLayer = window.dataLayer || [];
                dataLayer.push({
                    'event': 'listingScroll',
                    'ecommerce': JsonObj
                });
                lastCtr=intCtr;
            }
        });
    });
    <?php else: ?>
    {
        window.dataLayer = window.dataLayer || [];

        Array.prototype.push.apply(window.scProducts, <?php echo $_JsProducts; ?>);
        Array.prototype.push.apply(window.scProductUrls, <?php echo $_JsProductUrls; ?>);

        if (dataLayer.ecommerce === undefined) {
            var jsonObj = {
                'event': 'view_item_list',
                'ecommerce': {
                    'currencyCode': '<?php echo $helper->getCurrencyCode();?>',                       // Local currency is optional.
                    'impressions': window.scProducts
                }
            };
            dataLayer.push(jsonObj);
        } else {
            dataLayer.ecommerce.impressions = window.scProducts;
        }
    }
    <?php endif; ?>
    //]]>
</script>
