<?php
/**
 * @var $block \Scommerce\GoogleTagManagerPro\Block\ImpressionList
 */

$helper = $block->getHelper();
?>
<?php if ($helper->isEnhancedEcommerceEnabled()): ?>
<script>
    window.scDefaultList = '';

    var findProductInList = function (id, list) {
        for (var i in list) {
            if (list[i]['id'] == id) {
                return list[i];
            }
        }
        return '';
    };

    window.scGetProductImpression = function(productId) {
        var tmpIds = [];
        if (Array.isArray(productId)) {
            tmpIds = productId;
        } else {
            tmpIds.push(productId);
        }
        var tmpList = JSON.parse(localStorage.getItem('sc-gtm-data'));
        if (tmpList != null) {
            var tmp = tmpList['product_list'];
            for (var i in tmpIds) {
                var id = tmpIds[i];
                var item = findProductInList(id, tmp);
                if (item != '') {
                    return item;
                }
            }
        }
        return '';
    };

    window.scSetProductImpression = function(productId, list, category) {
        var tmpList = JSON.parse(localStorage.getItem('sc-gtm-data'));
        if (tmpList == null) {
            tmpList = [];
            tmpList.push({'id': productId, 'list': list, 'category': category});
            localStorage.setItem('sc-gtm-data', JSON.stringify({"product_list": tmpList}));
        } else {
            var tmp = tmpList['product_list'];
            var item = findProductInList(productId, tmp);
            if (item != '') {
                item['list'] = list;
                item['category'] = category;
            } else {
                tmp.push({'id': productId, 'list': list, 'category': category});
            }
            localStorage.setItem('sc-gtm-data', JSON.stringify({'product_list': tmp}));
        }
    };

    window.scClearProductImpressions = function () {
        localStorage.setItem('sc-gtm-data', null);
    };

    require(['jquery'], function($) {
        window.scGtmSaveImpression = function(productId, list, category) {
            $.cookie.domain = window.location.hostname;
            $.cookie('sc_list', list, {expires: new Date(new Date().getTime() + (1000 * 60 * 60 * 24))});
            $.cookie('sc_category', category, {expires: new Date(new Date().getTime() + (1000 * 60 * 60 * 24))});
            scSetProductImpression(productId, list, category);
        };

        $(document).on('click', 'a', function(e) {
            var product;
            var href = $(this).attr('href');
            var jsProductUrls = window.scProductUrls;
            //console.log(jsProductUrls)
            if (jsProductUrls != undefined) {
                var index = jsProductUrls.indexOf(href);

                if (index != -1) {
                    //event.preventDefault();
                    product = window.scProducts[index];
                    //console.log('clicked');
                    //console.log(product);
                    scGtmSaveImpression(product.id, product.list, product.category);
                    dataLayer.push({
                        'event': 'productClick',
                        'ecommerce': {
                            'click': {
                                'actionField': {'list': product.list},      // Optional list property.
                                'products': [{
                                    'name': product.name,                      // Name or ID is required.
                                    'id': product.id,
                                    'price': product.price,
                                    'brand': product.brand,
                                    'category': product.category,
                                    'position': product.position
                                }]
                            }
                        },
                        'eventCallback': function () {
                            if (!(e.ctrlKey || e.which == 2)) {
                                document.location = href;
                            }
                        }
                    });
                }
            }
        });
    });
</script>
<?php endif; ?>
