<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<script>
    function convertPromotions(trackingData, data) {
        if (data instanceof Array) {
            let result = [];
            for (let i=0; i < data.length; i++) {
                let promo = data[i];
                result.push({
                    item_name: promo.name,
                    item_id: promo.id,
                    index: promo.position,
                    creative_name: promo.creative
                });
            }
            return result;
        }
        return [];
    }
    function convertItemList(trackingData, data) {
        let impr = [];
        for (let i = 0; i < data.length; i++) {
            let product = data[i];
            impr.push({
                item_id: product.id,
                item_name: product.name,
                price: trackingData.formatPrice(product.price, false),
                item_brand: product.brand,
                item_list_name: product.list,
                item_list_id: trackingData.getListId(product.list),
                index: product.position,
                quantity: 1,
                affiliation: trackingData.getData('affiliation'),
                currency: trackingData.getData('currency')
            });
            let categories = product.category.split('->');
            impr[i]['item_category'] = categories[0];
            for (let j = 1; j < categories.length; j++) {
                key = 'item_category' + (j + 1);
                impr[i][key] = categories[j];
            }
        }
        return impr;
    }
    function convertAddToCartItem(trackingData, data) {
        let prods = [];
        for (let i = 0; i < data.length; i++) {
            prods.push({
                item_name: data[i].name,
                item_id: data[i].id,
                price: trackingData.formatPrice(data[i].price, false),
                item_brand: data[i].brand,
                quantity: data[i].quantity,
                item_list_name: data[i].list,
                item_list_id: trackingData.getListId(data[i].list),
                affiliation: trackingData.getData('affiliation'),
                currency: trackingData.getData('currency')
            });
            let categories = data[i].category.split('->');
            prods[i]['item_category'] = categories[0];
            for (let j = 1; j < categories.length; j++) {
                key = 'item_category' + (j + 1);
                prods[i][key] = categories[j];
            }
        }
        return prods;
    }
    function convertCheckoutItems(trackingData, data) {
        let prods = [];
        for (let i = 0; i < data.length; i++) {
            prods.push({
                item_name: data[i].name,
                item_id: data[i].id,
                price: trackingData.formatPrice(data[i].price, false),
                item_brand: data[i].brand,
                item_category: data[i].category,
                quantity: data[i].quantity,
                item_list_name: data[i].list,
                item_list_id: trackingData.getListId(data[i].list),
                affiliation: trackingData.getData('affiliation'),
                currency: trackingData.getData('currency')
            });
            let categories = data[i].category.split('->');
            prods[i]['item_category'] = categories[0];
            for (let j = 1; j < categories.length; j++) {
                key = 'item_category' + (j + 1);
                prods[i][key] = categories[j];
            }
        }
        return prods;
    }
    function convertPurchaseItems(trackingData, data) {
        let prods = [];
        for (let i = 0; i < data.length; i++) {
            prods.push({
                item_name: data[i].name,
                item_id: data[i].id,
                price: trackingData.formatPrice(data[i].price, false),
                item_brand: data[i].brand,
                item_list_name: data[i].list,
                item_list_id: trackingData.getListId(data[i].list),
                quantity: data[i].quantity,
                affiliation: trackingData.getData('affiliation'),
                currency: trackingData.getData('currency'),
                index: i + 1
            });
            let categories = data[i].category.split('->');
            prods[i]['item_category'] = categories[0];
            for (let j = 1; j < categories.length; j++) {
                key = 'item_category' + (j + 1);
                prods[i][key] = categories[j];
            }
        }
        return prods;
    }
    function convertWishlistItems(trackingData, data) {
        data = data.item;
        let prods = [];
        prods.push({
            item_name: data.name,
            item_id: data.id,
            price: trackingData.formatPrice(data.price, false),
            item_brand: data.brand,
            item_category: data.category,
            item_list_name: data.list,
            item_list_id: trackingData.getListId(data.list),
            quantity: data.quantity,
            affiliation: trackingData.getData('affiliation'),
            currency: trackingData.getData('currency'),
            index: 1
        });
        let categories = data.category.split('->');
        prods[0]['item_category'] = categories[0];
        for (let j = 1; j < categories.length; j++) {
            key = 'item_category' + (j + 1);
            prods[0][key] = categories[j];
        }
        return prods;
    }
</script>
