<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 */
/** @var \Scommerce\TrackingBase\ViewModel\TrackingDataContainer $viewModel */

$viewModel = $block->getData('view_model');
if (!$viewModel->isEnabled()) return;
?>

<script data-breeze <?= $viewModel->getNonce(); ?>>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking;

        tracking.fire('home_page', tracking.getPageType()?.toLowerCase() || "home");
    });
</script>
