<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var Scommerce\TrackingBase\ViewModel\TrackingDataContainer $viewModel */
$viewModel = $block->getData('view_model');
if (!$viewModel->isEnabled()) {
    return;
}
$productToBasket = $viewModel->getProductToBasket();
$productToWishlist = $viewModel->getProductToWishlist();
$skipPageReady = $block->getSkipPageReady();
?>
<script data-breeze>
    require([
        "jquery",
        "scTrackingData"
    ], function($, Tracking) {
        let tracking = Tracking;
        <?php if (!$skipPageReady): ?>
            $(document).one('breeze:load', function () {
                tracking.fire('page_ready', '<?=$viewModel->getPageType($block)?>' || "other");
            });
        <?php endif; ?>
    });
</script>
