<?php
/**
 * @var $block \Scommerce\GoogleTagManagerPro\Block\Adminhtml\Order\View
 */
$helper = $block->getHelper();

$refundOrder = $block->getRefundOrder();
$bGTM = false;
if ($refundOrder):
    $result = $refundOrder;
    $storeId =  $result["storeId"];
    if ($helper->isEnabled($storeId) && $helper->isEnhancedEcommerceEnabled($storeId)):
        $products = $result['products'];

        $intCtr = 0;
        $bGTM = true;
        ?>
        <script type="text/javascript">
            //<![CDATA[

            window.dataLayer = window.dataLayer || [];
            <?php if(!$result['fullRefund']):?>
            dataLayer.push({
                'event': 'refund',
                'ecommerce': {
                    'refund': {
                        'actionField': {'id': '<?php echo $result['orderId']?>'},        // Transaction ID.
                        'products': [
                            <?php foreach($products as $product):
                            $intCtr++;?>
                            {'id': '<?php echo $product['id']?>', 'quantity': <?php echo $product['qty']?>}<?php if ($intCtr != count($products)) echo ','?>
                            <?php endforeach;?>
                        ]
                    }
                }
            });
            <?php else:?>
            dataLayer.push({
                'event': 'refund',
                'ecommerce': {
                    'refund': {
                        'actionField': {'id': '<?php echo $result['orderId']?>'}         // Transaction ID. Required for purchases and refunds.
                    }
                }
            });
            <?php endif;
            $block->removeRefundOrderData();
            ?>
            //]]>
        </script>
    <?php endif;?>
<?php endif;?>

<?php
$orderData = $block->getOrderData();
if ($orderData):
    $result = $orderData;
    $storeId = $result['storeId'];
    if ($helper->isEnabled($storeId)
        && $helper->isEnhancedEcommerceEnabled($storeId)
        && $orderData
        && $helper->getSendAdminOrdersEnabled($storeId)):
        $products = $result['products'];

        $intCtr = 0;
        $bGTM = true;
        ?>
        <script type="text/javascript">
            //<![CDATA[
            window.dataLayer = window.dataLayer || [];
            <?php $intCtr=0;?>
            dataLayer.push({
                'event': 'purchase',
                'ecommerce': {
                    'currencyCode': '<?php echo $result['currency']?>',
                    'purchase': {
                        'actionField': {
                            'id': '<?php echo $result['id']?>',                         // Transaction ID. Required for purchases and refunds.
                            'affiliation': '<?php echo $result['affiliation'] ?>',
                            'revenue': '<?php echo $result['revenue']?>',                     // Total transaction value (incl. tax and shipping)
                            'tax': '<?php echo $result['tax']?>',
                            'shipping': '<?php echo $result['shipping']?>',
                            'coupon': '<?php echo $result['coupon']?>',
                            'source': '<?php echo $helper->getAdminSource($storeId) ?>',
                            'medium': '<?php echo $helper->getAdminMedium($storeId) ?>'
                        },
                        'products': [
                            <?php foreach($products as $item): ?>
                            <?php $intCtr++;?>
                            {
                                'name': '<?php echo $block->escapeHtml($item['name']) ?>',     // Name or ID is required.
                                'id': '<?php echo $block->escapeHtml($item['id']) ?>',
                                'price': '<?php echo $item['price']?>',
                                'brand': '<?php echo $block->escapeHtml($item['brand']) ?>',
                                'category': '<?php echo $block->escapeHtml($item['category']) ?>',
                                'quantity': <?php echo $item['quantity']?>
                                <?php if ($intCtr == count($products)):?>
                            }]
                        <?php else:?>
                    },
                    <?php endif;?>
                    <?php endforeach;?>
                }
            }
            });
            //]]>
        </script>
    <?php endif;
    $block->removeOrderData();
    ?>
<?php endif; ?>


<?php if ($bGTM): ?>
    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $helper->getAccountId($storeId) ?>"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $helper->getAccountId($storeId) ?>');</script>
    <!-- End Google Tag Manager -->
<?php endif; ?>
