<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Scommerce\GoogleTagManagerPro\Block\CookieScript $viewModel */
$viewModel = $block->getData('view_model');
$cookiesToSet = $viewModel->cookiesToSet();
if (!$viewModel->isEnabled() || !count($cookiesToSet)) {
    return;
}
?>

<script data-breeze <?= $viewModel->getNonce(); ?>>
    require([
        'jquery',
        'domReady!'
    ], function($) {
        var date = new Date();
        var lifetime = <?php echo $viewModel->cookieLifeTime(); ?>;
        date.setTime(date.getTime() + (lifetime * 24 * 60 * 60 * 1000));
        <?php foreach ($cookiesToSet as $cookie => $value) : ?>
        $.cookies.set('<?php echo $cookie ?>', '<?php echo $value ?>', {expires: date}); // Set Cookie Expiry Time
        <?php endforeach; ?>
    });
</script>
