<?php
/**
 * @var $block \Scommerce\GoogleTagManagerPro\Block\Gtm
 */
?>
<?php
/** @var \Scommerce\GoogleTagManagerPro\Helper\Data $helper */
$helper = $block->getHelper();
/** @var \Scommerce\GoogleTagManagerPro\ViewModel\Gtm $viewModel */

if (!$helper->isEnabled()) return;

$viewModel = $block->getViewModel();
$pageType = $viewModel->getPageType($block);
$useUa = $helper->useUaEvents();
$useGa4 = $helper->getAddGa4Events();
?>
<?php echo $block->getChildHtml('scom_gtm_ga4'); ?>

<!-- Scommerce Mage Google Tag Manager -->
<script data-breeze>
    window.dataLayer = window.dataLayer || [];
    require([
        'jquery',
        'scTrackingData',
        'remarketing',
        'mage/cookies'
    ], function($, Tracking, Remarketing) {
        let tracking = Tracking;
        let affiliation = '<?= $helper->getAffiliation() ?>';
        window.scStartGTM = function () {
            tracking.startEvents();
            <?php if ($helper->isGDPRCookieEnabled()): ?>
            let cookieKey = '<?php echo $helper->getCookieKey(); ?>';
            let isGDPRCookieForceDeclined = !!'<?php echo $helper->isGDPRCookieForceDeclined() ?>';

            function needShowTag() {
                if (cookieKey.length == 0) return true;
                var cookie = $.cookie('<?php echo $helper->getCookieKey() ?>');
                if (!isGDPRCookieForceDeclined) {
                    return !(cookie == null || cookie == "0");
                } else {
                    return cookie == "1";
                }
            }

            var startGtm = true;
            if (typeof window.scCookieChoices != 'undefined' && typeof window.scCookieChoices.enableGtmOrMarketing != 'undefined') {
                window.scCookieChoices.enableGtmOrMarketing()
                startGtm = window.ifEnableGtm;
                if (window.ifEnableGtm){
                    let date = new Date();
                    let minutes = 60 * 24 * 365;
                    date.setTime(date.getTime() + (minutes * 60 * 1000));
                    $.cookie('<?php echo $helper->getCookieKey() ?>', 1, { expires: date, path: '/' });
                }
            }
            if (needShowTag() == true && startGtm) {
                (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','<?php echo $helper->getAccountId() ?>');
            }
            <?php else: ?>
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','<?php echo $helper->getAccountId() ?>');
            <?php endif; ?>
        }
        setTimeout(function () {
            window.scStartGTM();
        },1050);

        $(document).one('breeze:load', function () {
            tracking.setData('affiliation', affiliation);

            tracking.subscribe('page_view', function(data) {
                // Page view implementation goes here
            });

            tracking.subscribe('home_page', function(data) {
                // Home page view implementation goes here
            });

            tracking.subscribe('page_ready', function(pageType) {
                <?php if ($helper->getDynamicRemarketingEnabled()): ?>
                let rdata = Remarketing(tracking, pageType, <?php echo $block->getRemarketingType() ?>, <?php echo $block->sendEcommCategoryPath() ?>);
                let event = 'fireRemarketingTag_' + pageType;
                dataLayer.push({
                    'event': event,
                    'google_tag_params': rdata
                });
                <?php endif; ?>
            });

            tracking.subscribe('promo_view', function(data) {
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'view_promotion',
                    'ecommerce': {
                        'items': convertPromotions(tracking, data)
                    }
                });
                <?php endif; ?>
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({ google_tag_params: null });
                dataLayer.push({
                    'ecommerce': {
                        'promoView': {
                            'promotions': data
                        }
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('promo_click', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({
                    'event': 'promotionClick',
                    'ecommerce': {
                        'promoClick': {
                            'promotions': [{
                                'id': data.id,
                                'name': data.name,
                                'creative': data.creative,
                                'position': data.position
                            }]
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'select_promotion',
                    'ecommerce': {
                        'items': [{
                            'promotion_id': data.id,
                            'promotion_name': data.name,
                            'creative_name': data.creative,
                            'location_id': data.position,
                            'creative_slot': data.slot
                        }]
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('view_list', function(data) {
                let impr = [];
                for (let i = 0; i < data.length; i++) {
                    let product = data[i];
                    impr.push({
                        id: product.id,
                        name: product.name,
                        price: tracking.formatPrice(product.price, false),
                        category: product.category,
                        brand: product.brand,
                        list: product.list,
                        position: product.position
                    });
                }
                <?php if ($useGa4): ?>
                dataLayer.push({
                    'event': 'view_item_list',
                    'ecommerce': {
                        'items': convertItemList(tracking, data)
                    }
                });
                <?php endif; ?>
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'ecommerce': {
                        'currencyCode': tracking.getCurrency(),
                        'impressions': impr
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('listing_scroll', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'listingScroll',
                    'ecommerce': {
                        'impressions': data
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'view_item_list',
                    'ecommerce': {
                        'items': convertItemList(tracking, data)
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('item_click', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({
                    'event': 'productClick',
                    'ecommerce': {
                        'click': {
                            'actionField': {'list': data.list},
                            'products': [{
                                'name': data.name,
                                'id': data.id,
                                'price': tracking.formatPrice(data.price, false),
                                'brand': data.brand,
                                'category': data.category,
                                'position': data.position
                            }]
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                let items = {
                    'item_name': data.name,
                    'item_id': data.id,
                    'price': tracking.formatPrice(data.price, false),
                    'item_brand': data.brand,
                    'item_list_name': data.list,
                    'item_list_id': tracking.getListId(data.list),
                    'index': data.position
                };
                if (affiliation !== '') {
                    items['affiliation'] = affiliation;
                }
                let categories = data.category.split('->');
                items['item_category'] = categories[0];
                for (let j = 1; j < categories.length; j++) {
                    key = 'item_category' + (j + 1);
                    items[key] = categories[j];
                }
                let content = {
                    'event': 'select_item',
                    'ecommerce': {
                        'items': [items]
                    }
                };
                dataLayer.push(content);
                <?php endif; ?>
            });

            tracking.subscribe('view_item', function(data) {
                let product = data;
                <?php if ($useGa4): ?>
                let items = {
                    item_name: product.name,
                    item_id: product.id,
                    price: tracking.formatPrice(product.price, false),
                    item_brand: product.brand
                };
                if (tracking.getData('affiliation') !== '') {
                    items['affiliation'] = tracking.getData('affiliation');
                }
                if (tracking.getSendDefaultList() == "1" || tracking.getDefaultList() != product.list) {
                    items["item_list_name"] = product.list;
                    items["item_list_id"] = tracking.getListId(product.list);
                }
                let categories = product.category.split('->');
                items['item_category'] = categories[0];
                for (let j = 1; j < categories.length; j++) {
                    key = 'item_category' + (j + 1);
                    items[key] = categories[j];
                }
                let content = {
                    'event': 'view_item',
                    'ecommerce': {
                        'items': [items]
                    }
                };
                dataLayer.push(content);
                <?php endif; ?>
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'ecommerce': {
                        'detail': {
                            'actionField': {'list': product.list},
                            'products': [{
                                name: product.name,
                                id: product.id,
                                price: tracking.formatPrice(product.price, false),
                                brand: product.brand,
                                category: product.category
                            }]
                        }
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('add_to_cart', function(data) {
                let prods = [];
                for (let i = 0; i < data.length; i++) {
                    let prod = {
                        'name': data[i].name,
                        'id': data[i].id,
                        'price': tracking.formatPrice(data[i].price, false),
                        'brand': data[i].brand,
                        'category': data[i].category,
                        'quantity': data[i].qty
                    };
                    if (tracking.getPageType() != 'product') {
                        prod['list'] = data[i].list;
                    }
                    prods.push(prod);
                }
                <?php if ($useUa): ?>
                dataLayer.push({
                    'event': 'addToCart',
                    'ecommerce': {
                        'currencyCode': tracking.getCurrency(),
                        'add': {
                            'products': prods
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'add_to_cart',
                    'ecommerce': {
                        'items': convertAddToCartItem(tracking, prods)
                    }
                });
                <?php endif; ?>
            });

            tracking.subscribe('remove_from_cart', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({
                    'event': 'removeFromCart',
                    'ecommerce': {
                        'currencyCode': tracking.getCurrency(),
                        'remove': {
                            'products': [{
                                'name': data.name,
                                'id': data.id,
                                'price': tracking.formatPrice(data.price, false),
                                'brand': data.brand,
                                'category': data.category,
                                'quantity': data.qty,
                                'list': data.list
                            }]
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                dataLayer.push({ ecommerce: null });
                let items = {
                    item_name: data.name,
                    item_id: data.id,
                    price: tracking.formatPrice(data.price, false),
                    item_brand: data.brand,
                    quantity: data.qty
                };
                if (tracking.getData('affiliation') !== '') {
                    items['affiliation'] = tracking.getData('affiliation');
                }
                if (tracking.getSendDefaultList() == "1" || tracking.getDefaultList() != data.list) {
                    items["item_list_name"] = data.list;
                }
                let categories = data.category.split('->');
                items['item_category'] = categories[0];
                for (let j = 1; j < categories.length; j++) {
                    key = 'item_category' + (j + 1);
                    items[key] = categories[j];
                }
                let content = {
                    'event': 'remove_from_cart',
                    'ecommerce': {
                        'items': [items]
                    }
                }
                dataLayer.push(content);
                <?php endif; ?>
            });

            <?php if ($helper->getAddGa4Events()): ?>
            tracking.subscribe('view_cart', function(data) {
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'view_cart',
                    'ecommerce': {
                        'currency': tracking.getData('currency'),
                        'value': tracking.getData('total'),
                        'items': convertCheckoutItems(tracking, data)
                    }
                });
            });
            <?php endif; ?>

            <?php if ($helper->getAddGa4Events()): ?>
            tracking.subscribe('add_to_wishlist', function(data) {
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'add_to_wishlist',
                    'ecommerce': {
                        'currency': tracking.getData('currency'),
                        'value': tracking.formatPrice(data.value, false),
                        'items': convertWishlistItems(tracking, data)
                    }
                });
            });
            <?php endif; ?>

            <?php if ($helper->getAddGa4Events()): ?>
            tracking.subscribe('begin_checkout', function(data) {
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'begin_checkout',
                    'ecommerce': {
                        'items': convertCheckoutItems(tracking, data)
                    }
                });
            });
            <?php endif; ?>

            tracking.subscribe('checkout_step', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'checkout',
                    'ecommerce': {
                        'checkout': {
                            'actionField': {step: data.step, option: data.option},
                            'products': data.products
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                if (data.stepType == 'shipment') {
                    dataLayer.push({ecommerce: null});
                    dataLayer.push({
                        'event': 'add_shipping_info',
                        'ecommerce': {
                            'currency': tracking.getData('currency'),
                            'value': tracking.getData('total'),
                            'coupon': tracking.getData('coupon'),
                            'shipping_tier': data.option,
                            'items': convertPurchaseItems(tracking, data.products)
                        }
                    });
                }
                if (data.stepType == 'payment') {
                    dataLayer.push({ecommerce: null});
                    dataLayer.push({
                        'event': 'add_payment_info',
                        'ecommerce': {
                            'currency': tracking.getData('currency'),
                            'value': tracking.getData('total'),
                            'coupon': tracking.getData('coupon'),
                            'payment_type': data.option,
                            'items': convertPurchaseItems(tracking, data.products)
                        }
                    });
                }
                <?php endif; ?>
            });

            tracking.subscribe('checkout_option', function(data) {
                <?php if ($useUa): ?>
                dataLayer.push({ ecommerce: null });
                dataLayer.push({
                    'event': 'checkoutOption',
                    'ecommerce': {
                        'checkout_option': {
                            'actionField': {step: data.step, option: data.option},
                        }
                    }
                });
                <?php endif; ?>
                <?php if ($useGa4): ?>
                if (data.stepType == 'shipment') {
                    dataLayer.push({ecommerce: null});
                    dataLayer.push({
                        'event': 'add_shipping_info',
                        'ecommerce': {
                            'currency': tracking.getData('currency'),
                            'value': tracking.getData('total'),
                            'coupon': tracking.getData('coupon'),
                            'shipping_tier': data.option,
                            'items': convertPurchaseItems(tracking, data.products)
                        }
                    });
                }
                if (data.stepType == 'payment') {
                    dataLayer.push({ecommerce: null});
                    dataLayer.push({
                        'event': 'add_payment_info',
                        'ecommerce': {
                            'currency': tracking.getData('currency'),
                            'value': tracking.getData('total'),
                            'coupon': tracking.getData('coupon'),
                            'payment_type': data.option,
                            'items': convertPurchaseItems(tracking, data.products)
                        }
                    });
                }
                <?php endif; ?>
            });

            <?php if ($pageType === "purchase"): ?>
            let purchaseData = tracking.getPurchaseData();
            <?php if ($useGa4): ?>
            dataLayer.push({
                'event': 'purchase',
                'ecommerce': {
                    transaction_id: purchaseData.id,
                    affiliation: tracking.getData('affiliation'),
                    value: tracking.formatPrice(purchaseData.revenue, false),
                    tax: tracking.formatPrice(purchaseData.tax, false),
                    shipping: tracking.formatPrice(purchaseData.shipping, false),
                    coupon: purchaseData.coupon,
                    currency: tracking.getCurrency(),
                    items: convertPurchaseItems(tracking, purchaseData.products)
                }
            });
            <?php endif; ?>
            <?php if ($useUa): ?>
            dataLayer.push({ ecommerce: null });
            dataLayer.push({
                'ecommerce': {
                    'currencyCode': tracking.getCurrency(),
                    'purchase': {
                        'actionField': {
                            'id': purchaseData.id,
                            'affiliation': tracking.getData('affiliation'),
                            'revenue': tracking.formatPrice(purchaseData.revenue, false),
                            'tax': tracking.formatPrice(purchaseData.tax, false),
                            'shipping': tracking.formatPrice(purchaseData.shipping, false),
                            'coupon': purchaseData.coupon
                        },
                        'products': purchaseData.products
                    }
                }
            });
            <?php endif; ?>
            <?php endif; ?>



        });
    });
</script>
<!-- Scommerce Mage End Google Tag Manager -->
