<?php
/**
 * @var $this Scommerce_GoogleTagManagerPro_Block_Gtm
 */
?>
<?php
$helper = $this->getHelper();?>
<!-- Scommerce Mage Google Tag Manager -->
<?php if ($helper->isServerSideEnabled()): ?>
    <?php echo $helper->getServerSideScriptNoScript() ?>
<?php else: ?>
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $helper->getAccountId() ?>"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<?php endif; ?>
<!-- Scommerce Mage End Google Tag Manager -->
